# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserv_id', models.CharField(max_length=50)),
                ('guest_name', models.CharField(max_length=100)),
                ('client_id', models.IntegerField()),
                ('hotel_id', models.IntegerField()),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
            ],
        ),
    ]
