# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100)),
                ('hotel_id', models.CharField(max_length=30)),
                ('account_id', models.CharField(max_length=30)),
            ],
        ),
    ]
