# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrate', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_addr', models.CharField(max_length=150)),
                ('cust_id', models.CharField(max_length=30)),
                ('account_id', models.CharField(max_length=30)),
            ],
        ),
    ]
