# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrate', '0004_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pay_freq',
            field=models.CharField(choices=[('0', 'Daily'), ('1', 'Weekly'), ('2', 'Monthly')], max_length=1),
        ),
    ]
