# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrate', '0005_auto_20170817_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comission',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='commission_type',
            field=models.CharField(choices=[('0', 'Amount'), ('1', 'Percentage')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
