# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartrate', '0006_auto_20170817_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comission', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trans_date', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartrate.Booking')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartrate.Contract')),
            ],
        ),
    ]
