# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrate', '0007_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel_id',
            field=models.CharField(max_length=50),
        ),
    ]
