# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrate', '0008_auto_20170908_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='corp_ref',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
